# Generated by Django 6.0.3 on 2026-04-19 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_course_name_en_course_name_ru_course_name_uz_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('status', models.CharField(choices=[('created', 'created'), ('success', 'success'), ('failed', 'failed')], default='created', max_length=20, verbose_name='status')),
                ('currency', models.CharField(choices=[('uzs', 'uzs'), ('usd', 'usd'), ('eur', 'eur'), ('rub', 'rub')], max_length=20, verbose_name='currency')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='courses.course', verbose_name='course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('vendor', models.CharField(choices=[('click', 'click'), ('payme', 'payme'), ('uzum', 'uzum'), ('other', 'other')], max_length=20, verbose_name='vendor')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed'), ('canceled', 'canceled')], max_length=20, verbose_name='status')),
                ('currency', models.CharField(choices=[('uzs', 'uzs'), ('usd', 'usd'), ('eur', 'eur'), ('rub', 'rub')], max_length=20, verbose_name='currency')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
            },
        ),
    ]
