# Generated by Django 6.0.3 on 2026-04-06 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='file_url',
        ),
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='media/', verbose_name='File URL'),
        ),
        migrations.AddField(
            model_name='region',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='common.country', verbose_name='country'),
        ),
    ]
