# Generated by Django 6.0.3 on 2026-04-08 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_media_file_url_media_file_region_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='file',
            new_name='file_url',
        ),
    ]
